### PR TITLE
fix(association): fix issue with translation and selected value

### PR DESCRIPTION
**Pull request by VMBindraban**

### CODE REVIEW

**Comment by doktordirk** [comment]
what's the issue?

**Comment by VMBindraban** [comment]
When using associations, the selected value becomes empty when you edit it.

**Comment by doktordirk** [comment]
edit what? i tried using the association select page in the todo app, and i didn't have an issue. 

anyways though, is just removing translation the only solution?

**Comment by VMBindraban** [comment]
When you create an entity with `association-selects` it works fine. If you want to edit the same entity, the stored value is empty. The stored value is being overridden bij de translation. (between the bind and the attached cycle)

**Comment by doktordirk** [comment]
so, maybe add  translation at 'attched'?

**Comment by VMBindraban** [comment]
How? The feature of using it as a attribute was so it wouldn't be needed as a dependency.

**Comment by RWOverdijk** [comment]
@VMBindraban Or figure out why this is happening. This is a bug. A translation should never affect the value of your dropdown. Ask on gitter and create an issue on i18n.

**Comment by VMBindraban** [comment]
Every application that hasn't updated i18n will have the bug. Besides that you can still translate it through the `placeholderText` binding.

**Comment by doktordirk** [comment]
so it.s fixed with an i18n update? then people either should do that or use an older/own version of  orm. but changing the current orm, still wouldn't be the solution

**Comment by VMBindraban** [comment]
Still need to figure out the precise problem, after that a make a issue in i18n if that was indeed the cause.

**Comment by VMBindraban** [comment]
Confirmed, it's a i18n issue. https://github.com/aurelia/i18n/issues/147

**Pull request closed without merging**
