### PR TITLE
Test

### PR DESCRIPTION
**Pull request by doktordirk**
travis test should fail

### CODE REVIEW

**Comment by doktordirk** [comment]
@RWOverdijk test failed but travis passed it?!

**Comment by RWOverdijk** [comment]
@doktordirk That is interesting. It might be this line: https://github.com/SpoonX/aurelia-orm/blob/master/build/tasks/test.js#L17 which was needed back when there was a bug that caused karma to take forever with returning anything.

**Comment by doktordirk** [comment]
tja, wasn't that

**Comment by RWOverdijk** [comment]
Woa... Then the exit code isn't 1.

**Comment by doktordirk** [comment]
ah, i saw at some time a karma issue mentioned. let me try that

**Comment by doktordirk** [comment]
fixed

**Pull request closed without merging**
