### PR TITLE
Hotfix markclean2

### PR DESCRIPTION
**Pull request by doktordirk**
that rebasing worked better. 
i made a minor bump as the behaviour changed

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@doktordirk It's a bug fix (contracted behavior), so it could be a patch bump.

**Comment by doktordirk** [comment]
Yeah. Wasnt sure. I.ll fix it later

On Mon, Jan 25, 2016 at 7:34 AM -0800, "Wesley Overdijk" notifications@github.com wrote:

@doktordirk It's a bug fix (contracted behavior), so it could be a patch bump.

---

**Comment by RWOverdijk** [comment]
Big :+1:!

**Comment by doktordirk** [comment]
was a good excercice

**Pull request merged**
