### PR TITLE
fix(build): current bundling with folders doesn't work.

### PR DESCRIPTION
**Pull request by doktordirk**
reverting 915814436235a27270249006309654b019a4904f

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@doktordirk Could you explain this PR to me? Is this based on something that was merged before?

**Comment by doktordirk** [comment]
you had merged it here https://github.com/SpoonX/aurelia-orm/pull/71

i didn't notice that folders didn't work before i tried to use a module from there now. seems though no one had since either !?

**Comment by RWOverdijk** [comment]
ah, alright. In that case, should it be reverted or fixed?

**Comment by doktordirk** [comment]
since it's they way aurelia.tools work currently, reverting is the better option for now.

**Comment by RWOverdijk** [comment]
I trust your judgement on this. 👍

**Comment by doktordirk** [comment]
no need. maybe i was stupid. i'd actually appreciate if you tried the previous version. maybe i was just too stupid (considering i had my trouble with orm lately)

**Pull request merged**
