### PR TITLE
fix(repository): prevent casting json type to string

### PR DESCRIPTION
**Pull request by VMBindraban**

### CODE REVIEW

**Review by RWOverdijk — APPROVED** [review]

**Comment by doktordirk** [comment]
where.s the difference between json and string types?!

**Comment by VMBindraban** [comment]
`json` is already parsed. Otherwise it will be converting it to a `string` resulting into `"[object object]"`.

**Comment by doktordirk** [comment]
but then it.s an plain old javascript object. jsons are strings.

**Comment by RWOverdijk** [comment]
@doktordirk Type json works as expected and returns an object. This is the case in regular systems. The only way around is to re-stringify which is silly.

**Pull request closed without merging**
