### PR TITLE
 fix(entity): do not delete id from request body in update calls

### LINKED ISSUE #185: Make deleting the id field before an update request optional
I usually design my PUT api like so:

```
[HttpPut]
public async Task<JsonResult> Put([FromBody] T item) {
    // ...
}
```

but after seeing the HTTP traffic from this plugin I had to change it to:

```
[HttpPut("{id}")]
public async Task<JsonResult> Put([FromRoute] Guid id, [FromBody] T item) {
    item.Id = id;
    // ...
}
```

See this thread if more context is needed: https://github.com/SpoonX/aurelia-api/issues/151

### PR DESCRIPTION
**Pull request by CuddleBunny**
Note: Didn't have permission to push the branch to the main project so I forked it.

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@CuddleBunny That's exactly how it should be done :)

Would you mind changing your commit message according to our [contributing guidelines](https://github.com/SpoonX/about/blob/master/CONTRIBUTING.md#commit)? This includes the "breaking change" part.

**Review by bas080 — APPROVED** [review]

**Comment by RWOverdijk** [comment]
Not exactly what I had in mind, your other commits are still there. But it's alright, I'll merge it later today.

**Comment by CuddleBunny** [comment]
Hmm, not sure why that happened. My local repository doesn't have all of that. I've not used GitHub a whole lot.

**Review by RWOverdijk — APPROVED** [review]

**Comment by RWOverdijk** [comment]
@CuddleBunny Published in a pre-release 5.0.0-1. If this works for the updaters, it will be released as stable.

**Pull request merged**
