### PR TITLE
Chore build test

### PR DESCRIPTION
**Pull request by doktordirk**
- task server' deprecated 'host' updated to 'hostname'

### CODE REVIEW

**Comment by doktordirk** [comment]
something went wrong here

**Comment by doktordirk** [comment]
issue above fix in https://github.com/SpoonX/aurelia-orm/pull/57

**Comment by doktordirk** [comment]
working, but will work on it more

**Comment by RWOverdijk** [comment]
:+1: (only curious what `transpiler: false` does)

**Comment by doktordirk** [comment]
nothing :smile:

**Comment by doktordirk** [comment]
that's all runtime transpilation and not even used in skeleton

**Pull request merged**
