### PR TITLE
fix(repository): retrieved single entitiy marked clean

### PR DESCRIPTION
**Pull request by doktordirk**
bug or feature? being returned unclean was at least unexpected.

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@doktordirk Nice catch! Could you add a test to verify this works?

**Comment by doktordirk** [comment]
i'd need to do after the other PR as the old version doesn't work

**Comment by doktordirk** [comment]
could test the test afterall

**Comment by RWOverdijk** [comment]
@doktordirk Awesome. I merged it, you can rebase (and prepare-release)

**Comment by doktordirk** [comment]
hmm, that didn't work as intended

**Pull request closed without merging**
