### PR TITLE
date default and update github token for travis

### PR DESCRIPTION
**Pull request by RWOverdijk**

### CODE REVIEW

**Comment by RWOverdijk** [comment]
https://github.com/SpoonX/aurelia-orm/pull/315

**Review by Rawphs — APPROVED** [review]

**Comment by RWOverdijk** [comment]
@gregoryagu Could you review? I changed it slightly because the implementation didn't work.

**Review by gregoryagu — APPROVED** [review]
I tested in my app and works great.

**Comment by RWOverdijk** [comment]
@gregoryagu Released v7.

**Comment by gregoryagu** [comment]
Thank you very much!

**Pull request merged**
