### PR TITLE
feat(project): typescript support

### PR DESCRIPTION
**Pull request by doktordirk**
- update to babel 6
- maybe jspm17 ready
- add lint-md task, remove unused doc task

### CODE REVIEW

**Comment by RWOverdijk** [comment]
Big one... I'll take my time for this tonight!

**Comment by doktordirk** [comment]
same as the others. only difference is the component. i'll recheck the d.ts with that

**Comment by doktordirk** [comment]
rechecked. d.ts should be fine. the build task differs slightly from the others. i dunno why, but the other way fails

**Comment by RWOverdijk** [comment]
I can't test this thoroughly right now... But it looks good at first glance. So I'll give you a :+1: trusting you tested this, and trusting the unit tests. :)

**Comment by doktordirk** [comment]
the code hasn't changed (basically). so no problems tobe expected

**Pull request merged**
