### PR TITLE
feat(property-decorators): make properties configurable

### PR DESCRIPTION
**Pull request by doktordirk**
Fixes an issue with babel's property decorator, which sets it non configurablen and thus prevents aurelia from binding properly

### CODE REVIEW

**Comment by doktordirk** [comment]
@RWOverdijk  good to go. please review

**Comment by RWOverdijk** [comment]
Looks good, quick Q though. We have more decorators, would we then need this everywhere? If so, we might as well create a base decorator or something.

**Comment by doktordirk** [comment]
it's only needed for property decorators. we don't have too many of those. nonetheless, yes, it should be centralized

**Review by RWOverdijk — APPROVED** [review]
👍

**Pull request merged**
